Fix #399 : Remove release data from measurements dashboard
mozilla/telemetry-dashboard pull request #419
Opened 2018-02-27 19:20 UTC by Sylvia23

The "release" channel and its versions removed from drop-down menu of both Measurement and Evolution Dashboards.

2018-02-27 19:44 UTC, chutten requested changes
Unfortunately it appears as though you've included the commits to a bunch of other issues in this pull request. Could you single it out to just a single commit? 

`git rebase -i` might be a good tool for this job (you can delete the other commits). Or you can checkout a new branch based against `mozilla:gh-pages` and then `cherry-pick` just the correct sha from `releasedata` over to your new branch and submit that as a pull request.

2018-02-27 20:29 UTC, Sylvia23 commented
Okay @chutten , I am looking into the matter. Will update you in a while. Thanks!

2018-02-28 15:24 UTC, georgf commented
Sorry, i was a bit to enthusiastic and didn't see Chris comment before.
It looks like we should first go through what Chris requested before digging into other details.

2018-02-28 15:48 UTC, Sylvia23 commented
@georgf This is good to review now.

2018-02-28 16:21 UTC, georgf reviewed
I tested this change locally and it seems to work well.
- I can't see "release" anymore as a choice in the dropdown.
- Using [a link](https://mzl.la/2ow5iGr) that contains the release channel with my local instance recovers and shows me the current Nightly data.

2018-02-28 16:21 UTC, georgf commented
Paging @chutten for a sanity code check.

2018-02-28 17:40 UTC, chutten commented
The code looks good. With @georgf's testing seeming to confirm it behaves well, I see no reason not to include this.

2018-02-28 17:40 UTC, chutten approved these changes

2018-02-28 17:40 UTC, merged