Npm command alternative
mozilla/telemetry-dashboard pull request #451
Opened 2018-03-08 00:21 UTC by rosexw

Hi Georg,

I have added an alternative command to running the web server using npm. I added this sentence to the bottom of the section: ### Working on the dashboard.

Rose

2018-03-08 14:28 UTC, georgf commented on probe-dictionary/explorer.css
> +.fixed-navbar {
It looks like some commits for #448 into this PR :)

2018-03-08 14:29 UTC, georgf commented
Chris, you probably have a more informed opinion on the README addition.

2018-03-08 19:32 UTC, chutten requested changes

2018-03-08 19:32 UTC, chutten commented on README.md
> +Alternatively, we can run on [npm web server](https://www.npmjs.com/package/http-server) using: `npm install http-server -g`
I would prefer this moved up closer to the instructions for the python web server, and presented in a similar way.

2018-03-08 21:09 UTC, rosexw commented
OK sure, I will edit this and then submit another pull request for review. 

Thank you for your feedback, Georg and Chris!

2018-03-08 22:26 UTC, chutten commented
You still need to remove the other unrelated changes Georg mentioned. And you get to remove the original npm mention.

Have you ever used `git rebase -i`? It might be very useful to you right now, allowing you to remove commits from your local repo that you don't want any more. You might want to `git checkout -b npm-instructions` to switch to a new branch first, in case you want to split your changes.

2018-03-09 01:26 UTC, rosexw commented
Removed the unrelated commits with `git rebase -i` and the outdated information.

Thanks, @chutten!

2018-03-09 18:35 UTC, chutten approved these changes

2018-03-09 18:36 UTC, merged

2018-03-09 18:36 UTC, chutten commented
Thank you for your contribution!