Add some tooltips to probe dictionary fields
mozilla/telemetry-dashboard pull request #566
Opened 2018-07-11 18:50 UTC by georgf

Start adding some tooltips to some probe dictionary fields.
These try to explain some of the potentially less clear fields.

2018-07-11 18:54 UTC, georgf commented
This is live for testing [here](https://georgf.github.io/telemetry-dashboard/probe-dictionary/).

2018-07-12 09:31 UTC, Dexterp37 commented
I don't want to sound picky on this, so pardon me :) I was thinking that maybe we should suggest users that there is a "tooltip", otherwise it's not easy to know. What about we add tooltip only on the headers and add a dashed underline where there's a tooltip? As shown [here](https://ux.stackexchange.com/a/80112/19101).

2018-07-12 09:37 UTC, badboy requested changes
Some typos for the current version, but I have some other things:

This adds the same text for every probe and is therefore not a more detailed explanation for that specific probe to look at.

Wouldn't it make more sense to change the text per probe to be more specific, e.g. release -> "This probe is only collected on Firefox release channel", pre-release -> "This probe is only collected on Firefox pre-release channels (beta & nightly).

And didn't @chutten propose an alternative saying making it more clear whether the version ranges are including or excluding the last version?

2018-07-12 09:37 UTC, badboy commented on probe-dictionary/explore.js
> +      tooltip: "Wether this probe collected on Firefox release or only on " +
```patch
- Wether this probe collected
+ Whether this probe is collected
```

2018-07-12 09:37 UTC, badboy commented on probe-dictionary/explore.js
> +               "when the probe was added, removed and it's expiry.",
```patch
- it's expiry
+ its expire
```

2018-07-12 09:37 UTC, badboy commented on probe-dictionary/index.html
> +        <tr title="Wether this probe collected on Firefox release or only on prerelease channels.">
```patch
- Wether this probe collected
+ Whether this probe is collected
```

2018-07-12 09:37 UTC, badboy commented on probe-dictionary/index.html
> +        <tr title="What versions this probe is actually recorded in. This depends on when the probe was added, removed and it's expiry.">
```patch
- it's expiry
+ its expiry
```

2018-07-12 14:56 UTC, georgf commented
>Wouldn't it make more sense to change the text per probe to be more specific, e.g. release -> "This probe is only collected on Firefox release channel", pre-release -> "This probe is only collected on Firefox pre-release channels (beta & nightly)

This sounds great, i'd take that to future improvements though as it's more work.
Having some static tooltips is better than having none.

2018-07-12 14:58 UTC, georgf commented
> @georgf , I don't want to sound picky on this, so pardon me :) I was thinking that maybe we should suggest users that there is a "tooltip", otherwise it's not easy to know. What about we add tooltip only on the headers and add a dashed underline where there's a tooltip? As shown here.

It doesn't sound picky & good points.
From user conversations and watching someone try this out, having tooltips around the place of confusion is important.
Underlining seems a bit noisy (visually) to me. I was thinking maybe adding a subtle info circle icon in a follow-up to aid discovery?

2018-07-12 14:59 UTC, Dexterp37 commented
> Underlining seems a bit noisy (visually) to me. I was thinking maybe adding a subtle info circle icon in a follow-up to aid discovery?

This  sounds like a good compromise to me!

2018-07-12 15:28 UTC, georgf commented
@badboy @Dexterp37 ready for another look

2018-07-12 16:02 UTC, Dexterp37 approved these changes
Looks good to me!

2018-07-12 16:16 UTC, badboy approved these changes

2018-07-12 18:28 UTC, merged